"""Changed type column for tags

Revision ID: fca00d1e7c3c
Revises: 
Create Date: 2023-09-09 19:00:49.277109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca00d1e7c3c'
down_revision = None
branch_labels = None
depends_on = None

enum_type = sa.Enum("bearer", name="token_type")

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'url', 'query', name='unique_values')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_date', sa.DateTime(), nullable=False),
    sa.Column('token_type', enum_type, nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    op.drop_table('adverts')
    enum_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
