"""Add index to id

Revision ID: 37b2c3d37f6e
Revises: fca00d1e7c3c
Create Date: 2023-09-09 19:43:36.258084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b2c3d37f6e'
down_revision = 'fca00d1e7c3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adverts_id'), 'adverts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adverts_id'), table_name='adverts')
    # ### end Alembic commands ###
